# Package name
# https://confluence.hl7.org/display/FHIR/NPM+Package+Specification#NPMPackageSpecification-Packagename
id: gold
canonical: https://www.vision-zero-oncology.de/fhir
name: GOLD
title: German Oncological Data Standard (GOLD)
description: Implementation Guide German Oncological Data Standard (GOLD)
status: draft
license: CC-BY-SA-4.0
copyright: CC-BY-SA-4.0
jurisdiction: urn:iso:std:iso:3166#DEU
date: 2022-03-28
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2021+
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters -> Parameter: releaselabel
releaseLabel: CI Build 
publisher:
  name: Berlin Institute of Health at Charité (BIH)
contact:
  name: Berlin Institute of Health at Charité (BIH)
  telecom:
    system: url
    value: https://www.bihealth.org/

dependencies:
  de.basisprofil.r4: 1.4.0
  de.gematik.isik-basismodul: 2.0.0
  de.medizininformatikinitiative.kerndatensatz.biobank: 1.0.3

pages:
  index.md:
    title: Home
  logicalmodel.md:
    title: Logical Model
  usecase.md:
    title: Use Case
  profiles.md:
    title: Profiles
  extensions.md:
    title: Extensions
  terminology.md:
    title: Terminology

# Parameters
# https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameter